export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const DELETE_USER = 'DELETE_USER';

export const SET_LINK_TOKEN = "SET_LINK_TOKEN";

export const ADD_LINKED_INSTITUTION = "ADD_LINKED_INSTITUTION";
export const SET_LINKED_INSTITUTIONS = "SET_LINKED_INSTITUTIONS";
export const DELETE_LINKED_INSTITUTION = "DELETED_LINKED_INSTITUTION";

export const ADD_ACCOUNTS = "ADD ACCOUNTS";
export const SET_ALL_ACCOUNTS = "SET_ALL_ACCOUNTS";
export const DELETE_ACCOUNTS = "DELETE_ACCOUNTS";
export const ACCOUNTS_LOADING = "ACCOUNTS_LOADING";

export const SET_PLAID_TRANSACTIONS = "SET_PLAID_TRANSACTIONS";
export const PLAID_TRANSACTIONS_LOADING = "PLAID_TRANSACTIONS_LOADING";

export const ADD_CASH_TRANSACTION = "ADD_CASH_TRANSACTION";
export const DELETE_CASH_TRANSACTION = "DELETE_CASH_TRANSACTION";
export const GET_CASH_TRANSACTIONS = "GET_CASH_TRANSACTIONS";
export const UPDATE_CASH_TRANSACTION = "UPDATE_CASH_TRANSACTION";